# Generated by Django 2.2.4 on 2019-09-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
