# Generated by Django 2.2.4 on 2019-09-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190902_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='pics'),
        ),
    ]
