# Generated by Django 2.2.4 on 2019-09-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20190904_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='img',
            field=models.ImageField(default='images/about.jpg', upload_to='pics'),
        ),
    ]
