# Generated by Django 2.2.4 on 2019-09-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190902_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='img',
            field=models.ImageField(default='destination_3.jpg', upload_to='img'),
        ),
    ]
