# Generated by Django 2.2.4 on 2019-09-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190902_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='img',
            field=models.ImageField(default='media/img/destination_3.jpg', upload_to='img'),
        ),
    ]
